// Cost Centers for Oxford House Staff Tracker
// Listed in alphabetical order as requested

export const COST_CENTERS = [
  'AL-SOR',
  'AL-SUBG',
  'AZ / CO',
  'AZ-BMC-SUBG',
  'AZ-CHCCP-SUBG (N)',
  'AZ-CHCCP-SUBG (S)',
  'AZ-MEDICAID-SUBG (N)',
  'CA / CO / NV',
  'CA-COCC-OSG',
  'CA-COCC-SUBG',
  'CA-SLOC-SUBG',
  'CO-EMSHIP-OSG',
  'CO-EMSHIP-SOR',
  'CO-EMSHIP-STATE',
  'CO-EMSHIP-SUBG',
  'CO-STATE',
  'CORPORATE',
  'CT / DE / ME',
  'DC / MD / VA',
  'DC-SOR',
  'DE / MD / VA',
  'DE-SOR',
  'DE-STATE',
  'FL-MEDICAID-OSG (N)',
  'FL-OSG',
  'FL-SOR',
  'FL-STATE',
  'FL-',
  'Finance',
  'IL / MN / WI',
  'IL-BCBS',
  'IL-SUBG',
  'IN / KY / IN',
  'IN-BCBS',
  'IN-STATE',
  'IN-SUBG',
  'IN-TO-OSG',
  'KY / IN / OH',
  'KY-OSG',
  'KY-SOR',
  'KY-SUBG',
  'KY-STATE',
  'LA-BCBS',
  'LA-SOR',
  'LA-SUBG',
  'MD-GRACE',
  'NC / TN',
  'NC-AHA',
  'NC-MEDICAID-DSG',
  'NC-SOR',
  'NC-SUBG',
  'NC-STATE',
  'NC-T-SOR',
  'NC-T-SUBG',
  'NC-TRELLIS',
  'NE-SOR',
  'NE-SOR (SUBG K)',
  'NE-SUBG',
  'NE-OSG',
  'NM-STATE',
  'NU-OSG',
  'NU-SOR',
  'NU-SOR (SUBG K)',
  'NV-MEDICAID',
  'NY',
  'NY-OCFS-OSG',
  'NY-OSG',
  'OK / MO / NE',
  'OK-GCI (RL-ENTRY)',
  'OK-KING',
  'OK-MO-STATE',
  'OK-SUBG',
  'OR-',
  'OR-OSG',
  'OR-STATE',
  'OH-CHCCP',
  'OH-OSG',
  'OH-OSG (FC)',
  'OH-SOR/OSG',
  'OH-STATE',
  'Program Services',
  'PS-UM-UMDD',
  'SC-PHCA',
  'SC-STATE',
  'TN-STATE',
  'TN-SUBG',
  'TX / NM',
  'TX-SUBG',
  'UN-END',
  'WA-',
  'WA-KING',
  'WA-OSG',
  'WA-SOR',
  'WA-SUBG',
] as const;

export type CostCenter = typeof COST_CENTERS[number];
